create extension if not exists pgcrypto;

create table users_information (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password text,
  session_id text,
  thread_id text,
  created_at timestamptz default now(),
  verification_code text,
  is_verified boolean default false,
  otp_pwd text,
  previous_response text,
  "last model response" text,
  "user information" jsonb
);

create table messages (
  id bigint generated by default as identity primary key,
  email text not null,
  thread_id text,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz default now()
  issue text
);
